AWSTemplateFormatVersion: 2010-09-09
Description: ---
Resources:
  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: aaa
      FunctionName: aaa
      Handler: aaa
      MemorySize: 128
      Role: role-arn
      Runtime: nodejs
      Timeout:
      VpcConfig:
        SecurityGroupIds:
          - sg-id
        SubnetIds:
          - subnet-id
      Environment:
        Variables:
          key1: value1 # A map of key-value pairs that the Lambda function can access
      Code:
        S3Bucket:
        S3Key:
        S3ObjectVersion:
        ZipFile:
      Tags:
        - Key: keyname
          Value: value
